/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blooming`; params?: Router.UnknownInputParams; } | { pathname: `/friends-feed`; params?: Router.UnknownInputParams; } | { pathname: `/garden`; params?: Router.UnknownInputParams; } | { pathname: `/gratitude-archive`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pruning`; params?: Router.UnknownInputParams; } | { pathname: `/search-users`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/blooming`; params?: Router.UnknownOutputParams; } | { pathname: `/friends-feed`; params?: Router.UnknownOutputParams; } | { pathname: `/garden`; params?: Router.UnknownOutputParams; } | { pathname: `/gratitude-archive`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pruning`; params?: Router.UnknownOutputParams; } | { pathname: `/search-users`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/blooming${`?${string}` | `#${string}` | ''}` | `/friends-feed${`?${string}` | `#${string}` | ''}` | `/garden${`?${string}` | `#${string}` | ''}` | `/gratitude-archive${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/pruning${`?${string}` | `#${string}` | ''}` | `/search-users${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/blooming`; params?: Router.UnknownInputParams; } | { pathname: `/friends-feed`; params?: Router.UnknownInputParams; } | { pathname: `/garden`; params?: Router.UnknownInputParams; } | { pathname: `/gratitude-archive`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pruning`; params?: Router.UnknownInputParams; } | { pathname: `/search-users`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
